spring:
  application:
    name: datile-it

  profiles:
    default: prod

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

jwt:
  secret: ${JWT_SECRET:default_test_secret_key_that_is_long_enough_12345}