http:
  routers:
    frontend:
      rule: "Host(`yourdomain.org`)"
      entryPoints:
        - web
        - websecure
      service: frontend
      tls:
        certResolver: myresolver

    backend:
      rule: "Host(`yourdomain.org`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: backend
      tls:
        certResolver: myresolver

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://datile-frontend:80"

    backend:
      loadBalancer:
        servers:
          - url: "http://datile-backend:8080"