ALTER TABLE user RENAME users;

ALTER TABLE assignees ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE priorities ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE statuses ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;